### PR TITLE
Formatting fixes to the kernel

### PR DESCRIPTION
**Pull request by Laar**
These fixes are generated by running `make format` on the master branch on my computer.

### CODE REVIEW

**Comment by JensWehner** [comment]
hmmm this should not happen, which clang-format version did you use?

**Comment by Laar** [comment]
I have version 10.0.0
```
/bin/clang-format --version
clang-format version 10.0.0
```

Kind of strange that it now starts complaining about different lines in the same files.

**Comment by JensWehner** [comment]
Yes so clang 9 and clang 10 differ in this formatting. So I would fix it to clang-9 atm?

**Comment by Laar** [comment]
Hmm, it seems that indeed installing and using clang-format 9 fixes this.

**Pull request closed without merging**
